// site/embeds/sandbox/vue-use-super-hover/src/App.vue
<template>
  <div class="page">
    <section class="panel" aria-labelledby="event-heading">
      <div class="event-toolbar" aria-live="polite">
        <span class="event-pill-label">Active:</span>
        <span class="event-pill">{{ activePill }}</span>
      </div>
      <div ref="rootRef" class="scroller" tabindex="0">
        <div
          v-for="n in itemCount"
          :key="'e' + n"
          class="row row--event"
          data-super-hover
          :data-row-id="String(n)"
        >
          <span class="row-label">Item {{ n }}</span>
        </div>
      </div>
    </section>
  </div>
</template>

<script setup lang="ts">
import { ref } from "vue";
import { useSuperHover } from "./super-hover-vue";

const itemCount = 180;
const activePill = ref("None");

const rootRef = useSuperHover({
  onEnter(e: Event) {
    const t = e.target;
    if (!(t instanceof HTMLElement)) return;
    const id = t.dataset.rowId;
    if (id) activePill.value = `Item ${id}`;
  },
  onLeave(e: Event) {
    const t = e.target;
    if (!(t instanceof HTMLElement)) return;
    if (t.dataset.rowId) activePill.value = "None";
  },
});
</script>

// site/embeds/sandbox/react-use-super-hover/src/App.tsx
import { useState } from "react";
import { useSuperHover } from "./super-hover-react";

const ITEM_COUNT = 180;

const superHoverRowProps = { "data-super-hover": "" } as const;

export default function App() {
  const [listRoot, setListRoot] = useState<HTMLDivElement | null>(null);
  const [activePill, setActivePill] = useState("None");

  useSuperHover(listRoot, {
    enabled: Boolean(listRoot),
    onEnter: (e) => {
      const t = e.target;
      if (!(t instanceof HTMLElement)) return;
      const id = t.dataset.rowId;
      if (id) setActivePill(`Item ${id}`);
    },
    onLeave: (e) => {
      const t = e.target;
      if (!(t instanceof HTMLElement)) return;
      if (t.dataset.rowId) setActivePill("None");
    },
  });

  return (
    <div className="page">
      <section className="panel" aria-labelledby="event-heading">
        <div className="event-toolbar" aria-live="polite">
          <span className="event-pill-label">Active:</span>
          <span className="event-pill">{activePill}</span>
        </div>
        <div ref={setListRoot} className="scroller" tabIndex={0}>
          {Array.from({ length: ITEM_COUNT }, (_, i) => (
            <div
              key={`e${i}`}
              className="row row--event"
              data-row-id={String(i + 1)}
              {...superHoverRowProps}
            >
              <span className="row-label">Item {i + 1}</span>
            </div>
          ))}
        </div>
      </section>
    </div>
  );
}
