// site/embeds/sandbox/svelte-events/src/App.svelte
<script lang="ts">
  import { onMount, onDestroy, tick } from "svelte";
  import {
    createSuperHover,
    type SuperHoverController,
    type SuperHoverMoveEventDetail,
  } from "./super-hover";

  const itemCount = 180;
  const items: number[] = Array.from({ length: itemCount }, (_, i) => i + 1);

  let paused = false;

  let elEvent: HTMLDivElement | undefined;
  let activePill = "None";
  let moveCount = 0;
  let movePoint = "—";
  let ctrl: SuperHoverController | undefined;
  let onEnter: ((e: Event) => void) | undefined;
  let onLeave: ((e: Event) => void) | undefined;
  let onMove: ((e: Event) => void) | undefined;
  let eventRoot: HTMLDivElement | undefined;

  onMount(async () => {
    await tick();
    if (!elEvent) return;
    eventRoot = elEvent;
    onEnter = (e) => {
      const t = e.target;
      if (!(t instanceof HTMLElement)) return;
      const id = t.dataset.rowId;
      if (id) activePill = `Item ${id}`;
    };
    onLeave = (e) => {
      const t = e.target;
      if (!(t instanceof HTMLElement)) return;
      if (t.dataset.rowId) activePill = "None";
    };
    onMove = (e) => {
      const detail = (e as CustomEvent<SuperHoverMoveEventDetail>).detail;
      moveCount += 1;
      movePoint = `${Math.round(detail.x)}, ${Math.round(detail.y)}`;
    };
    elEvent.addEventListener("superhoverenter", onEnter);
    elEvent.addEventListener("superhoverleave", onLeave);
    elEvent.addEventListener("superhovermove", onMove);
    ctrl = createSuperHover({ root: elEvent });
    if (paused) ctrl.pause();
  });

  function syncPause(): void {
    if (!ctrl) return;
    if (paused) ctrl.pause();
    else ctrl.resume();
  }

  onDestroy(() => {
    if (ctrl) ctrl.destroy();
    if (eventRoot && onEnter && onLeave && onMove) {
      eventRoot.removeEventListener("superhoverenter", onEnter);
      eventRoot.removeEventListener("superhoverleave", onLeave);
      eventRoot.removeEventListener("superhovermove", onMove);
    }
  });
</script>

<div class="page">
  <section class="panel" aria-labelledby="event-heading">
    <div class="event-toolbar" aria-live="polite">
      <span class="event-pill-label">Active:</span>
      <span class="event-pill">{activePill}</span>
      <span class="event-pill-label">Moves:</span>
      <span class="event-pill event-pill--metric">{moveCount}</span>
      <span class="event-pill-label">Last:</span>
      <span class="event-pill event-pill--metric">{movePoint}</span>
      <label class="event-toolbar-switch">
        <input type="checkbox" bind:checked={paused} on:change={syncPause} />
        Pause hit-test
      </label>
    </div>
    <div bind:this={elEvent} class="scroller" tabindex="0">
      {#each items as n (n + 10000)}
        <div
          class="row row--event"
          data-super-hover
          data-row-id={String(n)}
        >
          <span class="row-label">Item {n}</span>
        </div>
      {/each}
    </div>
  </section>
</div>

// site/embeds/sandbox/react-events/src/App.tsx
import { useEffect, useRef, useState } from "react";

import {
  createSuperHover,
  type SuperHoverController,
  type SuperHoverMoveEventDetail,
} from "./super-hover";

const ITEM_COUNT = 180;

const superHoverRowProps = { "data-super-hover": "" } as const;

export default function App() {
  const [eventRoot, setEventRoot] = useState<HTMLDivElement | null>(null);
  const [activePill, setActivePill] = useState("None");
  const [moveCount, setMoveCount] = useState(0);
  const [movePoint, setMovePoint] = useState("—");
  const [paused, setPaused] = useState(false);

  const ctrlRef = useRef<SuperHoverController | null>(null);

  useEffect(() => {
    if (!eventRoot) {
      ctrlRef.current?.destroy();
      ctrlRef.current = null;
      return;
    }

    ctrlRef.current?.destroy();
    const ctrl = createSuperHover({ root: eventRoot });
    ctrlRef.current = ctrl;

    const onEnter = (e: Event) => {
      const t = e.target;
      if (!(t instanceof HTMLElement)) return;
      const id = t.dataset.rowId;
      if (id) setActivePill(`Item ${id}`);
    };
    const onLeave = (e: Event) => {
      const t = e.target;
      if (!(t instanceof HTMLElement)) return;
      if (t.dataset.rowId) setActivePill("None");
    };
    const onMove = (e: Event) => {
      const detail = (e as CustomEvent<SuperHoverMoveEventDetail>).detail;
      setMoveCount((count) => count + 1);
      setMovePoint(`${Math.round(detail.x)}, ${Math.round(detail.y)}`);
    };

    eventRoot.addEventListener("superhoverenter", onEnter);
    eventRoot.addEventListener("superhoverleave", onLeave);
    eventRoot.addEventListener("superhovermove", onMove);

    return () => {
      eventRoot.removeEventListener("superhoverenter", onEnter);
      eventRoot.removeEventListener("superhoverleave", onLeave);
      eventRoot.removeEventListener("superhovermove", onMove);
      ctrl.destroy();
      ctrlRef.current = null;
    };
  }, [eventRoot]);

  useEffect(() => {
    const c = ctrlRef.current;
    if (!c) return;
    if (paused) c.pause();
    else c.resume();
  }, [paused, eventRoot]);

  return (
    <div className="page">
      <section className="panel" aria-labelledby="event-heading">
        <div className="event-toolbar" aria-live="polite">
          <span className="event-pill-label">Active:</span>
          <span className="event-pill">{activePill}</span>
          <span className="event-pill-label">Moves:</span>
          <span className="event-pill event-pill--metric">{moveCount}</span>
          <span className="event-pill-label">Last:</span>
          <span className="event-pill event-pill--metric">{movePoint}</span>
          <label className="event-toolbar-switch">
            <input
              type="checkbox"
              checked={paused}
              onChange={(e) => setPaused(e.target.checked)}
            />
            Pause hit-test
          </label>
        </div>
        <div ref={setEventRoot} className="scroller" tabIndex={0}>
          {Array.from({ length: ITEM_COUNT }, (_, i) => (
            <div
              key={`e${i}`}
              className="row row--event"
              data-row-id={String(i + 1)}
              {...superHoverRowProps}
            >
              <span className="row-label">Item {i + 1}</span>
            </div>
          ))}
        </div>
      </section>
    </div>
  );
}
